CREATE TABLE TEACHER_TABLE (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
teams_email VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
phone_number VARCHAR(255) NOT NULL,
hours VARCHAR(255) NOT NULL,
subject VARCHAR(255) NOT NULL,
shift VARCHAR(255) NOT NULL
);